name: CI/CD
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: ls -alih
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run build
      - run: ls -alih

  # test: