name: CI/CD
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run build
      - name: Cache node_modules and Cypress cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}

  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        browser: ['chrome', 'edge']
    steps:
      - uses: actions/checkout@v4
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
      - name: Cypress Run
        uses: cypress-io/github-action@v6
        with:
          install: false
          build: npm run build
          start: npm run start
          browser: ${{ matrix.browser }}
      - name: Upload Cypress Videos
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos
